#ifndef AETHER_CONFIG_H
#define AETHER_CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10
#define AETHER_TOTAL_INTERRUPTS 512

// 100MB
#define AETHER_HEAP_SIZE_BYTES 10485760
#define AETHER_HEAP_BLOCK_SIZE 4096
#define AETHER_HEAP_ADDRESS 0x01000000
#define AETHER_HEAP_TABLE_ADDRESS 0x00007E00

#define AETHER_SECTOR_SIZE 512

#define AETHER_MAX_PATH 108

#define AETHER_MAX_FILESYSTEMS 12
#define AETHER_MAX_FILE_DESCRIPTORS 512

#define AETHER_TOTAL_GDT_SEGMENTS 6

#define AETHER_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define AETHER_USER_PROGRAM_STACK_SIZE 1024 * 16
#define AETHER_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define AETHER_PROGRAM_VIRTUAL_STACK_ADDRESS_END AETHER_PROGRAM_VIRTUAL_STACK_ADDRESS_START - AETHER_USER_PROGRAM_STACK_SIZE

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#endif
